#!/usr/bin/env bash
npm install -S tachyons-background-position \
tachyons-background-size \
tachyons-base \
tachyons-border-colors \
tachyons-border-radius \
tachyons-border-style \
tachyons-border-widths \
tachyons-borders \
tachyons-box-shadow \
tachyons-box-sizing \
tachyons-clears \
tachyons-colors \
tachyons-coordinates \
tachyons-custom \
tachyons-debug \
tachyons-debug-grid \
tachyons-display \
tachyons-flexbox \
tachyons-floats \
tachyons-font-family \
tachyons-font-style \
tachyons-font-weight \
tachyons-forms \
tachyons-heights \
tachyons-hovers \
tachyons-images \
tachyons-letter-spacing \
tachyons-line-height \
tachyons-links \
tachyons-lists \
tachyons-max-widths \
tachyons-opacity \
tachyons-outlines \
tachyons-overflow \
tachyons-position \
tachyons-skins \
tachyons-skins-pseudo \
tachyons-spacing \
tachyons-tables \
tachyons-text-align \
tachyons-text-decoration \
tachyons-text-transform \
tachyons-type-scale \
tachyons-typography \
tachyons-utilities \
tachyons-vertical-align \
tachyons-visibility \
tachyons-white-space \
tachyons-widths \
tachyons-word-break \
tachyons-x-ray \
tachyons-z-index
